#!/bin/bash
# R2 存储快速配置指南

echo "🚀 Cloudflare R2 存储配置"
echo "================================"
echo ""
echo "✅ 已完成的步骤:"
echo "  1. ✅ Bucket 已创建: reelkey"
echo "  2. ✅ 公共访问已启用"
echo "  3. ✅ 配置脚本已准备"
echo ""
echo "📋 需要手动完成的步骤:"
echo ""
echo "步骤 1: 创建 API 令牌"
echo "  🔗 打开: https://dash.cloudflare.com/99a7580169295945d5e5f17af605d0c8/r2/api-tokens"
echo "  - 点击 'Create API Token'"
echo "  - Token Name: reelkey-api-token"
echo "  - Permissions: Object Read & Write"
echo "  - Bucket Scope: 仅 reelkey"
echo "  - 复制 Access Key ID 和 Secret Access Key"
echo ""
echo "步骤 2: 配置 CORS（可选，建议在 Dashboard 配置）"
echo "  🔗 打开: https://dash.cloudflare.com/99a7580169295945d5e5f17af605d0c8/r2/buckets/reelkey/settings"
echo "  - 找到 'CORS Policy' 部分"
echo "  - 添加规则:"
echo "    * Allowed Origins: *"
echo "    * Allowed Methods: GET, PUT, POST, DELETE, HEAD"
echo "    * Allowed Headers: *"
echo "    * Expose Headers: ETag"
echo "    * Max Age: 3600"
echo ""
echo "步骤 3: 运行配置脚本"
echo "  $ ./scripts/update-r2-env.sh"
echo "  输入刚才获取的 API 凭据"
echo ""
echo "步骤 4: 重启开发服务器"
echo "  $ pnpm dev"
echo ""
echo "📖 详细文档: docs/R2-STORAGE-SETUP.md"
echo ""
echo "💡 提示: 如果已经有 API 凭据，可以直接运行 update-r2-env.sh 脚本"
